### ISSUE TITLE
安装后初始化失败

### ISSUE THREAD

**Issue by xyjoey** [MercyCloudTeam/TomatoIDC#10]
环境Apache2.4 + PHP7.2 + MySQL5.5
也尝试了Nginx1.16 + Mariadb10.3 + PHP7.3
版本0.1.18
在数据库导入之后填写管理员信息进入/install/init时报错
`(2/2) QueryExceptionSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null (SQL: insert into `settings` (`name`, `value`, `updated_at`, `created_at`) values (setting.website.payment.alipay, , 2019-10-24 22:28:23, 2019-10-24 22:28:23))
in Connection.php line 664
at Connection->runQueryCallback('insert into `settings` (`name`, `value`, `updated_at`, `created_at`) values (?, ?, ?, ?)', array('setting.website.payment.alipay', null, '2019-10-24 22:28:23', '2019-10-24 22:28:23'), object(Closure))in Connection.php line 624
at Connection->run('insert into `settings` (`name`, `value`, `updated_at`, `created_at`) values (?, ?, ?, ?)', array('setting.website.payment.alipay', null, '2019-10-24 22:28:23', '2019-10-24 22:28:23'), object(Closure))in Connection.php line 459
at Connection->statement('insert into `settings` (`name`, `value`, `updated_at`, `created_at`) values (?, ?, ?, ?)', array('setting.website.payment.alipay', null, '2019-10-24 22:28:23', '2019-10-24 22:28:23'))in Connection.php line 411
at Connection->insert('insert into `settings` (`name`, `value`, `updated_at`, `created_at`) values (?, ?, ?, ?)', array('setting.website.payment.alipay', null, '2019-10-24 22:28:23', '2019-10-24 22:28:23'))in Processor.php line 32
at Processor->processInsertGetId(object(Builder), 'insert into `settings` (`name`, `value`, `updated_at`, `created_at`) values (?, ?, ?, ?)', array('setting.website.payment.alipay', null, '2019-10-24 22:28:23', '2019-10-24 22:28:23'), 'id')in Builder.php line 2615
at Builder->insertGetId(array('setting.website.payment.alipay', null, '2019-10-24 22:28:23', '2019-10-24 22:28:23'), 'id')in Builder.php line 1318
at Builder->__call('insertGetId', array(array('name' => 'setting.website.payment.alipay', 'value' => null, 'updated_at' => '2019-10-24 22:28:23', 'created_at' => '2019-10-24 22:28:23'), 'id'))in Model.php line 823
at Model->insertAndSetId(object(Builder), array('name' => 'setting.website.payment.alipay', 'value' => null, 'updated_at' => '2019-10-24 22:28:23', 'created_at' => '2019-10-24 22:28:23'))in Model.php line 788
at Model->performInsert(object(Builder))in Model.php line 651
at Model->save()in Builder.php line 790
at Builder->Illuminate\Database\Eloquent\{closure}(object(SettingModel))in helpers.php line 1027
at tap(object(SettingModel), object(Closure))in Builder.php line 791
at Builder->create(array('name' => 'setting.website.payment.alipay', 'value' => null))in ForwardsCalls.php line 23
at Model->forwardCallTo(object(Builder), 'create', array(array('name' => 'setting.website.payment.alipay', 'value' => null)))in Model.php line 1608
at Model->__call('create', array(array('name' => 'setting.website.payment.alipay', 'value' => null)))in Model.php line 1620
at Model::__callStatic('create', array(array('name' => 'setting.website.payment.alipay', 'value' => null)))in InstallController.php line 135
at InstallController->insertSettingSchema(object(Request))in InstallController.php line 51
at InstallController->installAction(object(Request))
at call_user_func_array(array(object(InstallController), 'installAction'), array(object(Request)))in Controller.php line 54
at Controller->callAction('installAction', array(object(Request)))in ControllerDispatcher.php line 45
at ControllerDispatcher->dispatch(object(Route), object(InstallController), 'installAction')in Route.php line 212
at Route->runController()in Route.php line 169
at Route->run()in Router.php line 682
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ThrottleRequests.php line 58
at ThrottleRequests->handle(object(Request), object(Closure), 60, '1')in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckInstallStatus.php line 35
at CheckInstallStatus->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php line 41
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 75
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 66
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 104
at Pipeline->then(object(Closure))in Router.php line 684
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 659
at Router->runRoute(object(Request), object(Route))in Router.php line 625
at Router->dispatchToRoute(object(Request))in Router.php line 614
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 31
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 31
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php line 27
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 62
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 151
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 104
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 55`

**Comment by YFsama** [comment]
运行 php artisan migrate 了嘛？

**Comment by xyjoey** [comment]
> 运行 php artisan migrate 了嘛？

是按照按照readme上的方法进行安装的，稍后尝试重新安装

> V0.1.8以及以后
> #克隆代码（国内用户可选Coding/Gitee）
> git clone --depth=1  https://github.com/MercyCloudTeam/TomatoIDC.git;
> #移动到目录
> cd TomatoIDC;
> #依赖安装
> composer install --no-dev
> #复制.env.example
> cp .env.example .env
> #访问安装页面完成安装
> https://domain/install

**Comment by xyjoey** [comment]
仍然不行 报相同错误
